EmployeePayrollMVC/Models/EmployeeDataModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EmployeePayrollMVC.Models
{
    public class EmployeeDataModel
    {
        [Key]
        public int EmployeeId { get; set; }
        [Required]
        [DisplayName("First Name")]
        [RegularExpression("^[A-Z]{1}[a-z]{2,}$", ErrorMessage = "First Name Start with capital letter and has minimum three character")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Department { get; set; }
        public int Salary { get; set; }
        [DisplayName("Start Date")]
        [DisplayFormat(DataFormatString ="{0:dd-MM-yyyy}")]
        public DateTime StartedDate { get; set; }
    }
}

EmployeePayrollMVC/Models/EmployeeInputDataModel.cs
using System;

namespace EmployeePayrollMVC.Models
{
    public class EmployeeInputDataModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Department { get; set; }
        public int Salary { get; set; }
    }
}

EmployeePayrollMVC/Models/EmployeePayrollDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace EmployeePayrollMVC.Models
{
    public class EmployeePayrollDbContext : DbContext
    {
        public EmployeePayrollDbContext(DbContextOptions options) : base(options)
        {
        }
        public DbSet<EmployeeDataModel> EmployeesDetails { get; set; }
    }
}

EmployeePayrollMVC/Models/ErrorViewModel.cs
using System;

namespace EmployeePayrollMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeePayrollMVC/Controllers/EmployeePayrollController.cs
using EmployeePayrollMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ActionNameAttribute = System.Web.Mvc.ActionNameAttribute;
using BindAttribute = Microsoft.AspNetCore.Mvc.BindAttribute;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using HttpDeleteAttribute = System.Web.Mvc.HttpDeleteAttribute;
using HttpGetAttribute = System.Web.Mvc.HttpGetAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using ValidateAntiForgeryTokenAttribute = System.Web.Mvc.ValidateAntiForgeryTokenAttribute;

namespace EmployeePayrollMVC.Controllers
{
    public class EmployeePayrollController : Controller
    {
        EmployeePayrollDbContext _dbContext;
        IConfiguration _configuration;
        
        public EmployeePayrollController(EmployeePayrollDbContext dbContext, IConfiguration configuration)
        {
            _dbContext = dbContext;
            _configuration = configuration; 
            
        }

        public IActionResult Getall()
        {
            try
            {
               
                return View(this._dbContext.EmployeesDetails.ToList());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public IActionResult GetByEmployeeId(int Id)
        {
            try
            {
                var empDetail = _dbContext.EmployeesDetails.Where(x => x.EmployeeId == Id).FirstOrDefault();
                return View(empDetail);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        //Get
        public IActionResult Remove(int Id)
        {
            try
            {
                var empInfo = _dbContext.EmployeesDetails.Where(x => x.EmployeeId == Id).FirstOrDefault();
                if (empInfo == null)
                {
                    return NotFound();
                }
                return View(empInfo);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        // POST
        [HttpPost,ActionName("RemoveConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveConfirmed(int Id)
        {
            try
            {
                var employeeDetail =  _dbContext.EmployeesDetails.Find(Id);
                if(employeeDetail == null)
                {
                    return NotFound();
                }
                _dbContext.EmployeesDetails.Remove(employeeDetail);
                _dbContext.SaveChanges();
                return Json(new { html = Helper.RenderRazorViewToString(this, "Getall", _dbContext.EmployeesDetails.ToList()) });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpGet]
        public IActionResult Add(int Id=0)
        {
            try
            {
               if(Id==0)
                {
                    return View(new EmployeeDataModel ());
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add( [Bind("EmployeeId,FirstName,LastName,Age,Department,Salary,StartedDate")] EmployeeDataModel employeeDataModel)
        {
            try
            {
               if(ModelState.IsValid)
                {
                    if(employeeDataModel != null)
                    {
                        employeeDataModel.StartedDate = DateTime.Now;
                        _dbContext.EmployeesDetails.Add(employeeDataModel);
                        _dbContext.SaveChanges();
                    }
                    return Json(new { IsValid = true, html = Helper.RenderRazorViewToString(this,"Getall",this._dbContext.EmployeesDetails.ToList())});
                }
                return Json(new { IsValid = false, html = Helper.RenderRazorViewToString(this, "Add", this._dbContext.EmployeesDetails.ToList()) });

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public IActionResult Edit(int Id =0)
        {
            try
            {
                if(Id == 0)
                {
                    return NotFound();
                }
                var employeeDataModel = _dbContext.EmployeesDetails.Find(Id);
                if (employeeDataModel == null)
                {
                    return NotFound();
                }
                return View(employeeDataModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id , EmployeeDataModel employeeDataModel)
        {
            try
            {
               
                if (ModelState.IsValid)
                {
                    if (Id != 0)
                    {
                        employeeDataModel.StartedDate = employeeDataModel.StartedDate;
                        _dbContext.EmployeesDetails.Update(employeeDataModel);
                        _dbContext.SaveChanges();
                    }
                    return Json(new { IsValid = true, html = Helper.RenderRazorViewToString(this, "Getall", this._dbContext.EmployeesDetails.ToList()) });
                }
                return Json(new { IsValid = false, html = Helper.RenderRazorViewToString(this, "Edit", this._dbContext.EmployeesDetails.ToList()) });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

EmployeePayrollMVC/Controllers/HomeController.cs
using EmployeePayrollMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeePayrollMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeePayrollMVC/Views/EmployeePayroll/Add.cshtml
@model EmployeePayrollMVC.Models.EmployeeDataModel

@{
    ViewData["Title"] = "Add";
}

<h1 class="btn btn-success text-white">Add Employee</h1>

<h4>Employee Detail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" asp-route-id="@Model.EmployeeId" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <input type="hidden" asp-for="EmployeeId" />
             <input type="hidden" asp-for="StartedDate" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Getall">Back to List</a>
</div>

EmployeePayrollMVC/Views/EmployeePayroll/Edit.cshtml
@model EmployeePayrollMVC.Models.EmployeeDataModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="btn btn-info text-black-50"><i class="fas fa-pencil"></i>Edit</h1>

<h4>Employee Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.EmployeeId" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeId" />
             <input type="hidden" asp-for="StartedDate" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Getall">Back to List</a>
</div>

EmployeePayrollMVC/Views/EmployeePayroll/GetByEmployeeId.cshtml
@model EmployeePayrollMVC.Models.EmployeeDataModel

@{
    ViewData["Title"] = "GetByEmployeeId";
}

<div>
    <h3 class="btn btn-info">Employee Details</h3>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EmployeeId"class="btn btn-info btn-block"><i class="fas fa-pencil"></i>Edit</a> 
    <a asp-action="Getall">Back to List</a>
</div>

EmployeePayrollMVC/Views/EmployeePayroll/Getall.cshtml
@model IEnumerable<EmployeePayrollMVC.Models.EmployeeDataModel>

@{
    ViewData["Title"] = "Getall";
}
    <div id="view-all">
<h1 class="text-center">All Employee Information</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartedDate)
            </th>
            <th> <a asp-action="Add" class="btn btn-success text-white">Add New Employee</a></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EmployeeId" class="btn btn-info text-white"><i class="fas fa-pencil"></i>Edit</a> 
                <a asp-action="GetByEmployeeId" asp-route-id="@item.EmployeeId" class="btn btn-info text-white">Details</a> 
                <a asp-action="Remove" asp-route-id="@item.EmployeeId" class="btn btn-danger text-white">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

EmployeePayrollMVC/Views/EmployeePayroll/Remove.cshtml
@model EmployeePayrollMVC.Models.EmployeeDataModel

@{
    ViewData["Title"] = "Remove";
}
<div>
    <h4>Employee Detail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartedDate)
        </dd>
    </dl>
    
    <form asp-action="RemoveConfirmed"asp-route-id="@Model.EmployeeId" onsubmit="return jQueryAjaxDelete(this);">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Delete" class="btn btn-danger btn-block" /> 
        <a asp-action="Getall">Back to List</a>
    </form>
</div>

EmployeePayrollMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeePayrollMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeePayrollMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="EmployeePayroll" asp-action="Getall">Employee Payroll</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeePayroll" asp-action="Add">Add Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeePayrollMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>